import http from 'node:http';
import {recordCharge,balanceSummary,estimateWorkflow,usageCost} from './billing.mjs';
import {deliverSuggestion,addSuggestionFocus,handToLibrarian} from './suggestions.mjs';
import {references,agentNames,createAgentRunner,draftWithAgents,checkScope} from './agents.mjs';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {resolveDataDirectory} from './runtime.mjs';
const exec=promisify(execFile), root=path.dirname(fileURLToPath(import.meta.url)), repo=path.dirname(root);
process.env.PYTHONUTF8='1';
const data=process.env.SHULL_DATA_DIR||resolveDataDirectory({appDirectory:root});fs.mkdirSync(data,{recursive:true});
const dbfile=path.join(data,'state.json');
let db=fs.existsSync(dbfile)?JSON.parse(fs.readFileSync(dbfile,'utf8')):{focus:[],runs:[]};
db.suggestions??=[];
db.templateNames??={};
db.billing??={starting:5,baselineIndex:0,since:new Date().toISOString(),ledger:[]};
for(const item of db.suggestions)if(item.status==='sending'){item.status='failed';item.error='The server restarted during the handoff. You can retry.';}
for(const r of db.runs)if(['Drafting','Building','Agent review'].includes(r.status)){for(const step of r.agents||[])if(step.status==='running')step.status='interrupted';r.status='Interrupted';r.error='The server restarted. Create a new request to retry.';}
const save=()=>{for(const r of db.runs)if(!['Failed','Interrupted'].includes(r.status))delete r.error;fs.writeFileSync(dbfile+'.tmp',JSON.stringify(db,null,2));fs.renameSync(dbfile+'.tmp',dbfile);};save();
let key=process.env.ANTHROPIC_API_KEY||'',model=db.selectedModel||'claude-sonnet-5',models=[];
const read=p=>fs.readFileSync(path.join(repo,p),'utf8');
const specs=fs.readdirSync(path.join(repo,'templates/worksheet/specs')).filter(x=>x.endsWith('.json')).map(name=>({id:name,spec:JSON.parse(read('templates/worksheet/specs/'+name))}));
const standards=['standards/QA_GATE.md','standards/VOICE.md','brand/SHULL_DESIGN_SYSTEM.md',...['chemistry','physics','geology'].map(c=>`courses/${c}/DECISIONS.md`)];
let port=Number(process.env.PORT||4317),origin=`http://127.0.0.1:${port}`;
async function anthropic(endpoint,body){const response=await fetch('https://api.anthropic.com/v1/'+endpoint,{method:body?'POST':'GET',headers:{'x-api-key':key,'anthropic-version':'2023-06-01','content-type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(180000)});const result=await response.json();if(!response.ok)throw Error(`Anthropic request failed (${response.status}). Check your key, model access, and API balance.`);return result;}
const agent=createAgentRunner({read,save,charge:(run,step,index)=>recordCharge(db.billing,run,step,index),request:body=>anthropic('messages',body),report:(run,step,index)=>{
const dir=path.join(data,'reports',run.id);fs.mkdirSync(dir,{recursive:true});
fs.writeFileSync(path.join(dir,index+'-'+step.role+'.md'),step.report);
}});
async function draft(run){try{await draftWithAgents(run,{read,agent,example:specs.find(s=>s.id===run.template).spec,validate:validateSpec,save,onResearch:async(run,research)=>{if(research.issues.length)await deliverSuggestion({run,research,agent,suggestions:db.suggestions,save});}});}catch(e){run.status='Failed';run.error=e.message;save();}}
async function reviewArtifact(run){
const dir=path.join(data,run.id);
const evidence={spec:run.spec,files:{docx:fs.existsSync(path.join(dir,'worksheet.docx')),pdf:fs.existsSync(path.join(dir,'worksheet.pdf'))},printAudit:run.audit||{status:'unavailable'},visualInspection:'not performed by an agent',separateKey:'not verified',drive:'not connected'};
const audit=await agent(run,'auditor','Review the built artifact evidence and content independently. No raster images are attached: visual QA is UNVERIFIED. Check every number. Distinguish content defects from checks still requiring teacher review. Never claim full QA passed.',evidence);
const filing=await agent(run,'librarian','Prepare a naming and filing recommendation from the repository architecture for this artifact. Drive is not connected: you cannot verify folders, retrieve canonical documents, or file anything. Report NOT FILED and list exact unresolved routing requirements.',{course:run.course,spec:run.spec,files:evidence.files});
await agent(run,'overseer','Produce the task report from the supplied evidence. Status must be INCOMPLETE because visual QA and canonical Drive filing are unverified. Name the remaining work and its owner. The teacher can inspect the local artifact.',{evidence,audit,filing});
run.status=audit.proceed&&run.audit?.status==='passed'?'Needs teacher review':'Agent needs attention';
run.reviewNote='Agent reports are available below. Full QA and canonical Drive filing are incomplete. Review the local document before classroom use.';
}
async function maintenance(run){try{
const checks=[];
for(const name of ['validate_agents.py','validate_references.py','validate_codes.py','validate_layers.py','validate_tokens.py']){
try{const result=await exec(process.env.SHULL_PYTHON||'python',[path.join(repo,'scripts',name)],{cwd:repo,timeout:60000,maxBuffer:200000});checks.push({name,status:'passed',output:result.stdout.slice(-16000)});}
catch(e){checks.push({name,status:'failed',output:String(e.stdout||e.stderr||e.message).slice(-16000)});}
}
const janitor=await agent(run,'janitor','Review these real validator results. This is a bounded maintenance sweep, not an exhaustive repository inspection. Report only; do not modify anything. Legacy material is excluded.',{checks});
await agent(run,'secretary','Turn actionable findings into PENDING proposal drafts using every change-control field. Unknown current-rule text must be marked needing evidence; do not invent it. These drafts are saved in local app reports, not canonical governance records. No changes are approved or implemented.',{janitor});
run.status='Report ready';
}catch(e){run.status='Failed';run.error=e.message;}save();}
async function build(run){try{const dir=path.join(data,run.id);fs.mkdirSync(dir,{recursive:true});const input=path.join(dir,'spec.json'),out=path.join(dir,'worksheet.docx');fs.writeFileSync(input,JSON.stringify(run.spec));const python=process.env.SHULL_PYTHON||'python';await exec(python,[path.join(repo,'templates/worksheet/build_worksheet_docx.py'),input,out],{cwd:repo,timeout:120000,maxBuffer:1000000});run.docx=true;if(process.env.SHULL_SOFFICE){await exec(process.env.SHULL_SOFFICE,['--headless',`-env:UserInstallation=${new URL('file:///'+dir.replaceAll('\\','/')+'/lo').href}`,'--convert-to','pdf','--outdir',dir,out],{timeout:120000});run.pdf=fs.existsSync(path.join(dir,'worksheet.pdf'));}
if(run.pdf){const auditScript=path.join(repo,'scripts/audit_worksheet.py');try{const audit=await exec(python,[auditScript,path.join(dir,'worksheet.pdf'),input],{cwd:repo,timeout:120000,maxBuffer:1000000});run.audit={status:'passed',summary:audit.stdout.trim().split(/\r?\n/).slice(-3).join('\n')};}catch(e){run.audit={status:'failed',summary:(e.stdout||e.stderr||e.message).trim().split(/\r?\n/).slice(-8).join('\n')};}}
run.status=run.audit?.status==='failed'?'Audit needs attention':'Needs teacher review';run.reviewNote=run.audit?.status==='passed'?'Built and passed the repository worksheet/page/ink audit. Review the content and visual preview before classroom use.':'Built, but the repository audit found an issue. Review the audit output before approval.';if(run.agents?.length){run.status='Agent review';save();await reviewArtifact(run);}}catch(e){run.status='Failed';run.error=('Worksheet build failed: '+(e.stderr||e.message)).slice(0,1800);}save();}
export function validateSpec(spec){if(!spec||!['chemistry','physics','geology'].includes(spec.course)||!Array.isArray(spec.sectionsContent))throw Error('Invalid worksheet specification');const scan=v=>{if(typeof v==='string'&&(/(?:file:|https?:|\.\.[/\\])/.test(v)))throw Error('External paths and URLs are not accepted in worksheet specifications');if(v&&typeof v==='object')for(const [k,x]of Object.entries(v)){if(/^(image|src|path|file|imagePath)$/i.test(k)&&x)throw Error('Image file references are not supported yet');scan(x);}};scan(spec);return spec;}
async function body(req){let b='';for await(const chunk of req){b+=chunk;if(b.length>200000)throw Error('Request too large');}return JSON.parse(b||'{}');}
const server=http.createServer(async(req,res)=>{const send=(code,obj)=>{res.writeHead(code,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(obj));};try{if(process.env.SHULL_DESKTOP_TOKEN&&req.headers['x-shull-desktop']!==process.env.SHULL_DESKTOP_TOKEN)return send(403,{error:'Desktop session required'});if(req.headers.host!==`127.0.0.1:${port}`&&req.headers.host!==`localhost:${port}`)return send(403,{error:'Invalid host'});if(req.method!=='GET'&&req.headers.origin!==origin&&req.headers.origin!==`http://localhost:${port}`)return send(403,{error:'Invalid origin'});const url=new URL(req.url,origin),p=url.pathname;
if(p==='/interface.js'){res.writeHead(200,{'content-type':'text/javascript'});return res.end(fs.readFileSync(path.join(root,'public/interface.js')));}
if(p==='/api/maintenance'&&req.method==='POST'){if(!key||!model)throw Error('Connect your Anthropic key and select a model first');if(db.runs.some(r=>['Drafting','Building','Agent review'].includes(r.status)))throw Error('Wait for the current workflow to finish');const run={id:randomUUID(),kind:'maintenance',course:'system',title:'Repository health review',model,created:new Date().toISOString(),status:'Agent review',agents:[]};db.runs.unshift(run);save();send(202,{id:run.id});void maintenance(run);return;}

if(p==='/api/suggestions/research'&&req.method==='POST'){
const b=await body(req);if(!['chemistry','physics','geology'].includes(b.course))throw Error('Select Chemistry, Physics, or Geology for a research briefing');
if(!key||!model)throw Error('Connect your Anthropic key in Settings first');
if(db.runs.some(r=>['Drafting','Building','Agent review'].includes(r.status)))throw Error('Wait for the current agent workflow to finish');
const run={id:randomUUID(),kind:'briefing',course:b.course,title:b.course[0].toUpperCase()+b.course.slice(1)+' teaching updates',model,created:new Date().toISOString(),status:'Agent review',agents:[]};
db.runs.unshift(run);save();send(202,{id:run.id});
void (async()=>{try{const research=await agent(run,'researcher','Review the supplied course decisions, current to-dos, and recent task metadata. Identify important notices and useful next steps. Distinguish actual findings from suggestions. Do not invent deadlines or claim to have read documents whose contents were not supplied. No live web or Drive access is available.',{focus:db.focus,recent:db.runs.filter(r=>r.course===run.course&&r.id!==run.id).slice(0,10).map(r=>({title:r.title,status:r.status,created:r.created}))});await deliverSuggestion({run,research,agent,suggestions:db.suggestions,save});run.status='Report ready';}catch(e){run.status='Failed';run.error=e.message;}save();})();return;}
const suggestionAction=p.match(/^\/api\/suggestions\/([\w-]+)\/(focus|dismiss|restore|librarian)$/);
if(suggestionAction&&req.method==='POST'){
const item=db.suggestions.find(x=>x.id===suggestionAction[1]);if(!item)throw Error('Suggestion not found');
const action=suggestionAction[2];
if(action==='focus'){addSuggestionFocus(item,db.focus);save();return send(200,{ok:true});}
if(action==='dismiss'||action==='restore'){if(item.status==='sending')throw Error('Wait for the Librarian response');item.dismissed=action==='dismiss';save();return send(200,{ok:true});}
if(item.status==='sending'||item.status==='response')throw Error('This notice has already been sent. Open the Librarian response.');
if(!key||!model)throw Error('Connect your Anthropic key in Settings first');
if(db.runs.some(r=>['Drafting','Building','Agent review'].includes(r.status)))throw Error('Wait for the current agent workflow to finish');
const run={id:randomUUID(),kind:'handoff',course:item.course,title:'Librarian: '+item.title,model,created:new Date().toISOString(),status:'Agent review',agents:[]};
item.status='sending';item.handoffRun=run.id;delete item.error;db.runs.unshift(run);save();send(202,{id:run.id});void handToLibrarian({item,run,agent,save});return;}

if(p==='/api/billing'&&req.method==='POST'){const b=await body(req);if(typeof b.balance!=='number'||!Number.isFinite(b.balance)||b.balance<0||b.balance>100000)throw Error('Enter a valid USD balance');db.billing.starting=b.balance;db.billing.baselineIndex=db.billing.ledger.length;db.billing.since=new Date().toISOString();save();return send(200,balanceSummary(db.billing));}
if(p==='/api/estimate'){const template=specs.find(t=>t.id===url.searchParams.get('template'));const kind=url.searchParams.get('kind')||'document';const roleList=kind==='build'?['auditor','librarian','overseer']:['overseer','researcher','secretary','designer','auditor','overseer','auditor','librarian','overseer'];const course=template?.spec.course||'chemistry';const chars={};for(const role of roleList){chars[role]=[`.claude/agents/${role}.md`,...(references[role]||[]),`courses/${course}/DECISIONS.md`].reduce((n,p)=>n+read(p).length,0)+JSON.stringify(template?.spec||{}).length+(url.searchParams.get('prompt')||'').slice(0,6000).length;}return send(200,{estimate:estimateWorkflow(model,roleList,chars)});}
if(p.match(/^\/api\/templates\/([\w.-]+)\/name$/)&&req.method==='POST'){const id=p.match(/^\/api\/templates\/([\w.-]+)\/name$/)[1],template=specs.find(x=>x.id===id);if(!template)throw Error('Template not found');const b=await body(req),name=String(b.name||'').trim();if(name.length<2||name.length>120)throw Error('Template name must be 2–120 characters');db.templateNames[id]=name;save();return send(200,{ok:true,id,name});}
if(p==='/api/state')return send(200,{...db,billing:balanceSummary(db.billing),runs:db.runs.map(r=>({...r,estimatedCost:r.sample?0:(r.agents||[]).reduce((n,a)=>n+(a.cost??usageCost(r.model,a.usage)??0),0),costUnknown:(r.agents||[]).some(a=>a.cost===null||(!a.usage&&['failed','interrupted'].includes(a.status)))})),agentNames,connected:!!key,model,models,templates:specs.map(x=>({id:x.id,course:x.spec.course,title:db.templateNames[x.id]||x.spec.sectionsContent.map(s=>s.title).join(', '),originalTitle:x.spec.sectionsContent.map(s=>s.title).join(', ')})),standards});
if(p==='/api/standard'){if(!standards.includes(url.searchParams.get('path')))return send(404,{});return send(200,{text:read(url.searchParams.get('path'))});}
if(p==='/api/connect'&&req.method==='POST'){const b=await body(req);key=String(b.key||key);if(!key)throw Error('Enter your Anthropic API key');try{models=(await anthropic('models')).data.map(m=>({id:m.id,name:m.display_name}));model=models.some(m=>m.id===model)?model:(models[0]?.id||'');db.selectedModel=model;save();}catch(e){key='';throw e;}return send(200,{ok:true});}
if(p==='/api/disconnect'&&req.method==='POST'){key='';models=[];model='';return send(200,{ok:true});}
if(p==='/api/model'&&req.method==='POST'){const b=await body(req);if(!models.some(m=>m.id===b.model))throw Error('Unknown model');model=b.model;db.selectedModel=model;save();return send(200,{ok:true});}
if(p==='/api/focus'&&req.method==='POST'){const b=await body(req);if(b.id){const f=db.focus.find(f=>f.id===b.id);if(f)f.done=!f.done;}else if(String(b.text||'').trim())db.focus.push({id:randomUUID(),text:String(b.text).slice(0,200),done:false});save();return send(200,{ok:true});}
if(p==='/api/runs'&&req.method==='POST'){const b=await body(req),template=specs.find(s=>s.id===b.template),route=['chemistry','physics','geology','class'].includes(b.course)?b.course:(template?.spec.course);if(!template)throw Error('Select a repository worksheet');if(!route)throw Error('Select a course');if(route!=='class'&&route!==template.spec.course)throw Error('Choose a template from the selected course');if(!b.sample&&(!key||!model))throw Error('Connect your Anthropic key and select a model first');if(!b.sample){checkScope(template.spec,read('courses/'+template.spec.course+'/DECISIONS.md'),route);if(db.runs.some(r=>['Drafting','Building','Agent review'].includes(r.status)))throw Error('Wait for the current workflow to finish');}if(b.model&&models.some(m=>m.id===b.model))model=b.model;const run={id:randomUUID(),template:template.id,course:route,templateCourse:template.spec.course,model,agents:[],title:template.spec.sectionsContent.map(s=>s.title).join(', '),prompt:String(b.prompt||'').slice(0,6000),created:new Date().toISOString(),status:b.sample?'Draft ready':'Drafting',sample:!!b.sample};if(b.sample)run.spec=structuredClone(template.spec);db.runs.unshift(run);save();send(201,{id:run.id});if(!b.sample)void draft(run);return;}
const revision=p.match(/^\/api\/runs\/([\w-]+)\/revise$/);
if(revision&&req.method==='POST'){const run=db.runs.find(r=>r.id===revision[1]);if(!run||run.status!=='Agent needs attention'||!run.spec)throw Error('No revision-ready draft');if(!key||!model)throw Error('Reconnect Anthropic first');if(db.runs.some(r=>['Drafting','Building','Agent review'].includes(r.status)))throw Error('Wait for the current workflow to finish');run.prompt=(run.prompt||'')+'\nRevise these independent review findings:\n'+(run.agents||[]).filter(x=>x.role==='auditor').slice(-1).map(x=>x.report).join('\n');run.docx=false;run.pdf=false;delete run.audit;run.status='Drafting';run.model=model;save();send(202,{id:run.id});void draft(run);return;}
const match=p.match(/^\/api\/runs\/([\w-]+)\/(build|approve|teach)$/);if(match&&req.method==='POST'){const run=db.runs.find(r=>r.id===match[1]);if(!run)throw Error('Request not found');if(match[2]==='build'){if(!['Draft ready','Needs teacher review'].includes(run.status)||!run.spec)throw Error('Draft is not ready');if(run.agents?.length&&(!key||!model))throw Error('Reconnect Anthropic to run the independent artifact review');validateSpec(run.spec);run.status='Building';save();send(202,{ok:true});void build(run);return;}if(match[2]==='approve'){if(run.status!=='Needs teacher review')throw Error('Build and review the document first');run.status='Teacher approved';}else{if(run.status!=='Teacher approved')throw Error('Approve before recording paper assignment');run.status='Handed out';run.taughtAt=new Date().toISOString();}save();return send(200,{ok:true});}
const file=p.match(/^\/files\/([\w-]+)\/(worksheet\.(docx|pdf))$/);if(file){const target=path.join(data,file[1],file[2]);if(!fs.existsSync(target))return send(404,{});res.writeHead(200,{'content-type':file[3]==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','content-disposition':`${file[3]==='pdf'?'inline':'attachment'}; filename="${file[2]}"`});fs.createReadStream(target).pipe(res);return;}
const staticFiles={'/':'index.html','/app.js':'app.js','/style.css':'style.css'};if(staticFiles[p]){res.writeHead(200,{'content-type':p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html','content-security-policy':"default-src 'self'; style-src 'self'; script-src 'self'; frame-src 'self'; object-src 'none'; base-uri 'none'"});return res.end(fs.readFileSync(path.join(root,'public',staticFiles[p])));}send(404,{error:'Not found'});
}catch(e){send(400,{error:e.message});}});
export function startServer(requestedPort=port){return new Promise((resolve,reject)=>{server.once('error',reject);server.listen(requestedPort,'127.0.0.1',()=>{server.removeListener('error',reject);port=server.address().port;origin=`http://127.0.0.1:${port}`;resolve(server);});});}
if(process.argv[1]===fileURLToPath(import.meta.url))startServer().then(()=>console.log(`SHULL OS ready at ${origin}`));
